apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: management-cluster
    kustomize.toolkit.fluxcd.io/namespace: kommander
  name: codecentric
  namespace: kommander-flux
spec:
  interval: 10m
  timeout: 1m
  url: https://codecentric.github.io/helm-charts
